import os
os.system("pkg install toilet")
os.system("clear") 
print("by Fandi63")
print("===========================")
os.system("toilet -f mono12 -F gay IPhack")
print("===========================") 
os.system("COLOR2='\033[92m'")
os.system("echo -e $COLOR")
input("Press Enter::")
os.system("clear")
print("hacking....")
os.system("clear") 
os.system("ping zscvrch.cz") 
print("Back to main menu? Press enter to continue") 
os.system("python iphack.py")
